Repository openshift/openshift-state-metrics, pull requests merged in 2019-05, with the labels that each got.

#13 Route metric information
  .gitignore
  manifests/openshift-state-metrics-cluster-role.yaml
  pkg/collectors/builder.go
  pkg/collectors/route.go
  pkg/collectors/route_test.go
  pkg/options/collector.go
Labels: approved, ok-to-test, size/L

#15 Update the deployment manifests
  manifests/openshift-state-metrics-deployment.yaml
Labels: approved, lgtm, size/XS

#16 Add BlueShells to owners
  OWNERS
Labels: approved, lgtm, size/XS

#17 Update the imagePullPolicy to Always
  manifests/openshift-state-metrics-deployment.yaml
Labels: approved, lgtm, size/XS

#18 Add some docs for the metrics
  Makefile
  docs/README.md
  docs/build-metrics.md
  docs/buildconfig-metrics.md
  docs/cli-arguments.md
  docs/clusterresourcequota-metrics.md
  docs/deploymentconfig-metrics.md
  docs/route-metrics.md
  pkg/collectors/build_test.go
  pkg/collectors/cluster_resource_quota_test.go
  pkg/collectors/route_test.go
Labels: approved, lgtm, size/L

#19 Update root Readme to point to docs
  README.md
Labels: approved, lgtm, size/XS

#22 Fix typo in build completion metric help
  pkg/collectors/build.go
Labels: approved, lgtm, size/XS

#26 Use jsonnet to generate the manifests
  .gitignore
  Makefile
  README.md
  hack/build-jsonnet.sh
  jsonnet/jsonnetfile.json
  jsonnet/jsonnetfile.lock.json
  jsonnet/main.jsonnet
  jsonnet/openshift-state-metrics.libsonnet
  manifests/openshift-state-metrics-cluster-role-binding.yaml
  manifests/openshift-state-metrics-cluster-role.yaml
  manifests/openshift-state-metrics-deployment.yaml
  manifests/openshift-state-metrics-role-binding.yaml
  manifests/openshift-state-metrics-role.yaml
  manifests/openshift-state-metrics-service-account.yaml
  manifests/openshift-state-metrics-service-monitor.yaml
  manifests/openshift-state-metrics-service.yaml
Labels: approved, lgtm, size/XL
