Repository openshift/openshift-state-metrics, pull requests merged in 2019-04, with the labels that each got.

#7 Intialize OWNERS
  OWNERS
Labels: lgtm, size/XS

#8 Update Readme
  README.md
Labels: lgtm, size/XS, ¯\_(ツ)_/¯

#10 Update docker file to use openshift base image
  Dockerfile
  Makefile
Labels: approved, lgtm, size/S

#11 Remove travis testing icon
  README.md
Labels: approved, lgtm, size/XS
