Repository openshift/openshift-state-metrics, pull requests merged in 2019-07, with the labels that each got.

#30 This update the ksonet version and deployment api version.
  jsonnet/openshift-state-metrics.libsonnet
  manifests/openshift-state-metrics-deployment.yaml
Labels: approved, lgtm, size/S

#31 Update makefile
  Makefile
Labels: approved, lgtm, size/XS

#32 Update the jsonnet file and manifests
  jsonnet/openshift-state-metrics.libsonnet
  manifests/openshift-state-metrics-deployment.yaml
Labels: approved, lgtm, size/S

#33 Remove role/rolebinding for addon resizer
  jsonnet/openshift-state-metrics.libsonnet
  manifests/openshift-state-metrics-role-binding.yaml
  manifests/openshift-state-metrics-role.yaml
Labels: approved, size/M

#34 Fix usage of $GOPATH in Makefile
  Makefile
Labels: approved, lgtm, size/XS

#35 Use modules from vendor dir on build
  Dockerfile
  Makefile
Labels: approved, lgtm, size/XS

#36 Update service definition
  jsonnet/openshift-state-metrics.libsonnet
  manifests/openshift-state-metrics-service.yaml
Labels: approved, lgtm, size/XS

#37 use ga kubelet os label
  jsonnet/openshift-state-metrics.libsonnet
  manifests/openshift-state-metrics-deployment.yaml
Labels: approved, lgtm, size/XS

#38 Fix/Extension for ClusterResourceQuotas
  docs/clusterresourcequota-metrics.md
  pkg/collectors/cluster_resource_quota.go
  pkg/collectors/cluster_resource_quota_test.go
Labels: ok-to-test, size/L

#39 Fix/Extension for ClusterResourceQuotas
  docs/clusterresourcequota-metrics.md
  pkg/collectors/cluster_resource_quota.go
  pkg/collectors/cluster_resource_quota_test.go
Labels: approved, lgtm, ok-to-test, size/XS
