Repository openshift/openshift-state-metrics, pull requests merged in 2020-10, with the labels that each got.

#59 Bug 1885249: Replace glog with klog v2
  go.mod
  go.sum
  main.go
  pkg/collectors/build.go
  pkg/collectors/build_config.go
  pkg/collectors/builder.go
  pkg/collectors/cluster_resource_quota.go
  pkg/collectors/deployment_config.go
  pkg/collectors/group.go
  pkg/collectors/route.go
  vendor/github.com/go-logr/logr/LICENSE
  vendor/github.com/go-logr/logr/README.md
  vendor/github.com/go-logr/logr/go.mod
  vendor/github.com/go-logr/logr/logr.go
  vendor/github.com/golang/glog/README
  vendor/k8s.io/klog/v2/.gitignore
  vendor/k8s.io/klog/v2/CONTRIBUTING.md
  vendor/k8s.io/klog/v2/LICENSE
  vendor/k8s.io/klog/v2/OWNERS
  vendor/k8s.io/klog/v2/README.md
  vendor/k8s.io/klog/v2/RELEASE.md
  vendor/k8s.io/klog/v2/SECURITY_CONTACTS
  vendor/k8s.io/klog/v2/code-of-conduct.md
  vendor/k8s.io/klog/v2/go.mod
  vendor/k8s.io/klog/v2/go.sum
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klog_file.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#61 Bug 1886111: Revert "Merge pull request #59 from paulfantom/klog"
  go.mod
  go.sum
  main.go
  pkg/collectors/build.go
  pkg/collectors/build_config.go
  pkg/collectors/builder.go
  pkg/collectors/cluster_resource_quota.go
  pkg/collectors/deployment_config.go
  pkg/collectors/group.go
  pkg/collectors/route.go
  vendor/github.com/go-logr/logr/LICENSE
  vendor/github.com/go-logr/logr/README.md
  vendor/github.com/go-logr/logr/go.mod
  vendor/github.com/go-logr/logr/logr.go
  vendor/github.com/golang/glog/LICENSE
  vendor/github.com/golang/glog/README
  vendor/github.com/golang/glog/glog.go
  vendor/github.com/golang/glog/glog_file.go
  vendor/k8s.io/klog/v2/.gitignore
  vendor/k8s.io/klog/v2/CONTRIBUTING.md
  vendor/k8s.io/klog/v2/OWNERS
  vendor/k8s.io/klog/v2/README.md
  vendor/k8s.io/klog/v2/RELEASE.md
  vendor/k8s.io/klog/v2/SECURITY_CONTACTS
  vendor/k8s.io/klog/v2/code-of-conduct.md
  vendor/k8s.io/klog/v2/go.mod
  vendor/k8s.io/klog/v2/go.sum
  vendor/modules.txt
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#60 Updating openshift-state-metrics builder & base images to be consistent with ART
  Dockerfile
Labels: approved, lgtm

#62 Bug 1885249: Replace glog with klog v2
  go.mod
  go.sum
  main.go
  pkg/collectors/build.go
  pkg/collectors/build_config.go
  pkg/collectors/builder.go
  pkg/collectors/cluster_resource_quota.go
  pkg/collectors/deployment_config.go
  pkg/collectors/group.go
  pkg/collectors/route.go
  pkg/options/options.go
  vendor/github.com/go-logr/logr/LICENSE
  vendor/github.com/go-logr/logr/README.md
  vendor/github.com/go-logr/logr/go.mod
  vendor/github.com/go-logr/logr/logr.go
  vendor/github.com/golang/glog/README
  vendor/k8s.io/klog/v2/.gitignore
  vendor/k8s.io/klog/v2/CONTRIBUTING.md
  vendor/k8s.io/klog/v2/LICENSE
  vendor/k8s.io/klog/v2/OWNERS
  vendor/k8s.io/klog/v2/README.md
  vendor/k8s.io/klog/v2/RELEASE.md
  vendor/k8s.io/klog/v2/SECURITY_CONTACTS
  vendor/k8s.io/klog/v2/code-of-conduct.md
  vendor/k8s.io/klog/v2/go.mod
  vendor/k8s.io/klog/v2/go.sum
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klog_file.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
